version: '2'

volumes:
  settings:                          # Only required if using PERSISTENT flag (see below)

services:

  browser:
    build: ./chromium
    privileged: true # required for UDEV to find plugged in peripherals such as a USB mouse
    network_mode: host
    restart: always

  notify:
    restart: "on-failure"
    privileged: true
    build: ./notify
